/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum ChatType {
    Private = "private",
    Group = "group",
    Public = "public",
}

/** @internal */
export const ChatType$ = z.nativeEnum(ChatType);
