/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum PaymentTerm {
    Net = "net",
    CashInAdvance = "cash-in-advance",
    CashWithOrder = "cash-with-order",
    CashBeforeShipment = "cash-before-shipment",
    DeferredPayment = "deferred-payment",
    Prepayment = "prepayment",
    Installment = "installment",
    Net30 = "net-30",
    Net60 = "net-60",
    Net90 = "net-90",
    DueOnReceipt = "due-on-receipt",
    DueEndOfMonth = "due-end-of-month",
    CashOnDelivery = "cash-on-delivery",
    Prepaid = "prepaid",
    UponCompletion = "upon-completion",
    Custom = "custom",
}

/** @internal */
export const PaymentTerm$ = z.nativeEnum(PaymentTerm);
