/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum ProductAvailabilityStatus {
    InStock = "in-stock",
    OutOfStock = "out-of-stock",
    BackOrder = "back-order",
    PreOrder = "pre-order",
    Discontinued = "discontinued",
}

/** @internal */
export const ProductAvailabilityStatus$ = z.nativeEnum(ProductAvailabilityStatus);
