/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ReactionType, ReactionType$ } from "./reactiontype";
import { z } from "zod";

export type Reactions = {
    userId?: string | undefined;
    messageId?: string | undefined;
    chatId?: string | undefined;
    type?: ReactionType | undefined;
    createdAt?: Date | undefined;
};

/** @internal */
export namespace Reactions$ {
    export type Inbound = {
        userId?: string | undefined;
        messageId?: string | undefined;
        chatId?: string | undefined;
        type?: ReactionType | undefined;
        createdAt?: string | undefined;
    };

    export const inboundSchema: z.ZodType<Reactions, z.ZodTypeDef, Inbound> = z
        .object({
            userId: z.string().optional(),
            messageId: z.string().optional(),
            chatId: z.string().optional(),
            type: ReactionType$.optional(),
            createdAt: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.userId === undefined ? null : { userId: v.userId }),
                ...(v.messageId === undefined ? null : { messageId: v.messageId }),
                ...(v.chatId === undefined ? null : { chatId: v.chatId }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.createdAt === undefined ? null : { createdAt: v.createdAt }),
            };
        });

    export type Outbound = {
        userId?: string | undefined;
        messageId?: string | undefined;
        chatId?: string | undefined;
        type?: ReactionType | undefined;
        createdAt?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Reactions> = z
        .object({
            userId: z.string().optional(),
            messageId: z.string().optional(),
            chatId: z.string().optional(),
            type: ReactionType$.optional(),
            createdAt: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.userId === undefined ? null : { userId: v.userId }),
                ...(v.messageId === undefined ? null : { messageId: v.messageId }),
                ...(v.chatId === undefined ? null : { chatId: v.chatId }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.createdAt === undefined ? null : { createdAt: v.createdAt }),
            };
        });
}
