/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum TaskStatus {
    Todo = "todo",
    InProgress = "in-progress",
    Done = "done",
    Blocked = "blocked",
    OnHold = "on-hold",
    Cancelled = "cancelled",
}

/** @internal */
export const TaskStatus$ = z.nativeEnum(TaskStatus);
